### ISSUE TITLE
오타 발견 !!1

### ISSUE THREAD

**Issue by rootkwak528** [daehyun1023/Computer-Science#1]
https://github.com/daehyun1023/Computer-Science/tree/master/Linux-%EB%A8%B8%EC%8B%A0-%EA%B5%AC%ED%95%98%EA%B8%B0/%EA%B8%B0%EB%B3%B8%EA%B3%BC%EC%A0%9C

WSL 설치 방법
3. windows terminal을 실행
    * **wihndows** 터미널에서 power shell, 명령 프롬프트, azure cloud shell을 사용할 수 있다.
    * 위에 wi(h)ndows 에서 h가 빠져야 함 ㅋㅋ

사실.. 이슈 만드는거 한번 해보고 싶어서 해봤습니다.

**Comment by daehyun1023** [comment]
오.. 버그픽스 감사합니다 ㅋㅋㅋ
